### PR TITLE
Update joy to 5.0.0-beta.51

### PR DESCRIPTION
**Pull request by samutoljamo-pareto**
Errors didn't disappear after React 19 backport. I think this is because joy UI uses an old version of @mui/base. I made a ticket in material UI's repo: https://github.com/mui/material-ui/issues/44738

### CODE REVIEW

**Comment by samutoljamo-pareto** [comment]
Update: Seems like new React 19 backport PR has been merged, but no release yet

**Comment by samutoljamo-pareto** [comment]
No warnings anymore, but I didn't update our app to React 19. There are a few libraries that are not updated.

This one hasn't been updated in a while and it states React 16-18 as peer dep: https://www.npmjs.com/package/use-resize-observer
Also:

**Review by Fuzzbender — APPROVED** [review]
I have no idea of the implications of the update, but let's do it. :)

**Review by korva — APPROVED** [review]
Works for me and the warnings are gone 👍

**Pull request merged**
